### ISSUE TITLE
Provide more info

### ISSUE THREAD

**Issue by sharu725** [mkhangg/academic-website#1]
Please add the following repo info

## Add About template
![image](https://github.com/mkhangg/academic-website/assets/8033084/fce28c3d-9f82-436a-9a6c-2ad1af619d79)

## Add Preview image
![image](https://github.com/mkhangg/academic-website/assets/8033084/e0f7d9d1-db61-46cc-899f-3d73ce211ae9)

**Comment by mkhangg** [comment]
@sharu725: Added repo description and social preview image!
